### ISSUE TITLE
make jumbotron & background params

### ISSUE THREAD

**Issue by N6REJ** [N6REJ/mod_bearstestimonials#1]
These REALLY need to be params, check the [video](https://www.youtube.com/watch?v=cNjzoDmlC1M) for details.

**Comment by N6REJ** [comment]
@RussW

**Comment by C-Lodder** [comment]
@N6REJ Ok, I've installed the module locally to get an idea of how it works and looked at the video to see what you're trying to achieve.

Transversing up the DOM and checking for the appropriate `<div>` to add the jumbotron background to will make your life very hard because:

1. Not everyone uses Bootstrap, so checking for `row` and `container` won't always work
2. If they are using Bootstrap, they simply may not be using those exact classes.
3. Some users may be asyncrounously manipulating the DOM...e.g they may be generating some markup on the fly, and your background might be assigned to the wrong element.

So what I'd suggest doing, is opening your `default.php` and wrap all the contents inside an additional container:

```
<div class="bear-container">
    <?php if ( $params->get('jpreload') == '1' ) : ?>
    ....
    ....
</div>
```

It will then be up to the user to set the width of the testimonals module to the desired width using a module class suffix, such as `col-md-6`

**Comment by N6REJ** [comment]
TYVM! I'll give that a go!

**Comment by C-Lodder** [comment]
@N6REJ https://github.com/N6REJ/mod_bearstestimonials/pull/2

**Comment by N6REJ** [comment]
is there a way to "break" the container from within bears-container?

**Comment by C-Lodder** [comment]
@N6REJ Do you mean have the background image attached to an element outside of `.container`? If so, then there will not be a 100% concrete way to do this. It's up to the template to deal with that

**Comment by N6REJ** [comment]
yeah, thats what I meant, ok, then they can manually add the image to the custom.css
